DROP DATABASE IF EXISTS stew_db;

CREATE DATABASE stew_db;
USE stew_db;

CREATE TABLE stew
(
id INT NOT NULL AUTO_INCREMENT,
stew_name VARCHAR(200),
devoured BOOLEAN DEFAULT false,
date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(id)
);